 <?php if ($this->admin == null): ?>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-login">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-6">
                            <a href="#" class="active" id="login-form-link">Se connecter</a>
                        </div>
                        <div class="col-xs-6">
                            <a href="#" id="register-form-link">S'enregistrer</a>
                        </div>
                    </div>
                    <hr>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <form id="login-form" action="<?php echo $this->url(array('controller' => 'index', 'action' => 'index', 'type' => 'signin'), null, true); ?>" method="post" role="form" style="display: block;">
                                <div class="form-group">
                                    <input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Pseudo" value="">
                                </div>
                                <div class="form-group">
                                    <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Mot de passe">
                                </div>
                                <div class="form-group text-center">
                                    <input type="checkbox" tabindex="3" class="" name="remember" id="remember">
                                    <label for="remember"> Se souvenir de moi</label>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Connection">
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-lg-12">
                                            <div class="text-center">
                                                <a href="#" tabindex="5" class="forgot-password">Mot de passe oublié?</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <form id="register-form" action="<?php echo $this->url(array('controller' => 'index', 'action' => 'index', 'type' => 'signup'), null, true); ?>" method="post" role="form" style="display: none;">
                                <div class="form-group">
                                    <input type="text" name="lastname" id="username" tabindex="1" class="form-control" placeholder="Nom" value="">
                                </div>
                                <div class="form-group">
                                    <input type="text" name="firstname" id="username" tabindex="1" class="form-control" placeholder="Prénom" value="">
                                </div>
                                <div class="form-group">
                                    <input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Pseudo" value="">
                                </div>
                                <div class="form-group">
                                    <input type="email" name="email" id="email" tabindex="1" class="form-control" placeholder="Adresse email" value="">
                                </div>
                                <div class="form-group">
                                    <input type="tel" name="phone" id="username" tabindex="1" class="form-control" placeholder="numéro de téléphone" value="">
                                </div>
                                <div class="form-group">
                                    <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="mot de passe">
                                </div>
                                <div class="form-group">
                                    <input type="password" name="confirm-password" id="confirm-password" tabindex="2" class="form-control" placeholder="Mot de passe de confirmation">
                                </div>
                                <div class="form-group">
                                    <input type="text" name="address" id="username" tabindex="2" class="form-control" placeholder="Adresse">
                                </div>
                                <div class="form-group">
                                    <input type="text" name="cp" id="username" tabindex="2" class="form-control" placeholder="Code postal">
                                </div>
                                <div class="form-group">
                                    <input type="text" name="ville" id="username" tabindex="2" class="form-control" placeholder="Ville">
                                </div>
                                <div class="form-group">
                                    <input type="text" name="pays" id="username" tabindex="2" class="form-control" placeholder="Pays">
                                </div>
                                <div class="form-group text-center">
                                    <input type="checkbox" tabindex="3" class="" name="newsletter" id="remember">
                                    <label for="remember"> S'abonner au newsletter</label>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Enregistrer">
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>