        </div>
    </div>
    <footer id="footer">
        <style>
            #social:hover {
    			-webkit-transform:scale(1.1); 
                        -moz-transform:scale(1.1); 
                        -o-transform:scale(1.1); 
                                                }
                                                #social {
                                                        -webkit-transform:scale(0.8);
                                        /* Browser Variations: */
                        -moz-transform:scale(0.8);
                        -o-transform:scale(0.8); 
                        -webkit-transition-duration: 0.5s; 
                        -moz-transition-duration: 0.5s;
                        -o-transition-duration: 0.5s;
                                                }           
                        /* 
                            Only Needed in Multi-Coloured Variation 
                                                                       */
                                                .social-fb:hover {
                                                        color: #3B5998;
                                                }
                                                .social-tw:hover {
                                                        color: #4099FF;
                                                }
                                                .social-gp:hover {
                                                        color: #d34836;
                                                }
                                                .social-em:hover {
                                                        color: #f39c12;
                                                }
        </style>
        <div class="container">
            <hr>
                <div class="text-center center-block">
                    <a href="https://www.facebook.com/bootsnipp"><i id="social" class="fa fa-facebook-square fa-3x social-fb"></i></a>
                    <a href="https://twitter.com/bootsnipp"><i id="social" class="fa fa-twitter-square fa-3x social-tw"></i></a>
                    <a href="https://plus.google.com/+Bootsnipp-page"><i id="social" class="fa fa-google-plus-square fa-3x social-gp"></i></a>
                    <a href="mailto:bootsnipp@gmail.com"><i id="social" class="fa fa-envelope-square fa-3x social-em"></i></a>
                </div>
            <hr>
        </div>
    </footer>
</body>
<script>
    $(document).ready(function(){
    $(".dropdown").hover(            
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
            $(this).toggleClass('open');        
        },
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
            $(this).toggleClass('open');       
        }
    );
});

$(function() {

    $('#login-form-link').click(function(e) {
		$("#login-form").delay(100).fadeIn(100);
 		$("#register-form").fadeOut(100);
		$('#register-form-link').removeClass('active');
		$(this).addClass('active');
		e.preventDefault();
	});
	$('#register-form-link').click(function(e) {
		$("#register-form").delay(100).fadeIn(100);
 		$("#login-form").fadeOut(100);
		$('#login-form-link').removeClass('active');
		$(this).addClass('active');
		e.preventDefault();
	});

});
</script>
</html>