<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><?= $this->firstname." ".$this->lastname ?></h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class=" col-md-9 col-lg-9 "> 
                            <table class="table table-user-information">
                                <tbody>
                                    <tr>
                                        <td>Adresse mail</td>
                                        <td><a href="mailto:<?=   $this->email ?>"><?=   $this->email ?></a></td>
                                    </tr>
                                    <tr>
                                        <td>telephone</td>
                                        <td><?=   $this->telephone ?></td>
                                    </tr>
                                    <tr>
                                        <td>Adresse</td>
                                        <td><?=   $this->address ?></td>
                                    </tr>

                                    <tr>
                                    <tr>
                                        <td>Ville</td>
                                        <td><?=   $this->ville ?></td>
                                    </tr>
                                    <tr>
                                        <td>Pays</td>
                                        <td><?=   $this->pays ?></td>
                                    </tr>
                                    <tr>
                                        <td>Code Postal</td>
                                        <td><?=   $this->codepostale ?></td>
                                    </tr>
                                <td>Abonner au newsletter</td>
                                <td><?=   $this->newsletter == 1?'Oui':'Non' ?></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <a data-original-title="Broadcast Message" data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>
                    <span class="pull-right">
                        <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'modify'), null, true); ?>" data-original-title="Edit this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a>
<!--                        <a data-original-title="Remove this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a>-->
                    </span>
                </div>

            </div>
        </div>
    </div>
</div>